name = 'altv-mango-vue-tailwind-starter'
host = '0.0.0.0'
port = 7788
players = 5
announce = false
gamemode = 'altv-mango-vue-tailwind-starter'
website = 'TODO'
language = 'en'
description = 'TODO'
modules = ['js-module-v2']
resources = ['core', 'watch-server']
debug = true